/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projectGC.view;

import com.projectGC.model.ProjectGConsole;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Defier
 */
public class projectGC extends javax.swing.JFrame {
private final LinkedList<ProjectGConsole> consoleList=new LinkedList<ProjectGConsole>();
private java.awt.CardLayout cardLayout;
    /**
     * Creates new form projectGC
     */
    public projectGC()
    {
        initComponents();
        initializeLayout();
        initializeData();
    }
    
public void addConsoleToTable(){
     DefaultTableModel model = (DefaultTableModel) tblCartDetails.getModel();
    model.setRowCount(0);
    for (ProjectGConsole Console:consoleList){
        model.addRow(new Object[]{Console.getConsoleName(),Console.getBrand(),Console.getQuantity(),Console.getReleaseDate()});

}}
private Boolean UpdateCart(ProjectGConsole Console) {
        String Name = Console.getConsoleName();
        for (ProjectGConsole Consoleupdate :consoleList ) {
            if (Name.equals(Consoleupdate.getConsoleName())) 
                Consoleupdate.setBrand(Console.getBrand());
                Consoleupdate.setQuantity(Console.getQuantity());
                Consoleupdate.setReleaseDate(Console.getReleaseDate());
                Consoleupdate.setReleaseDate(Console.getReleaseDate());
               addConsoleToTable();
                return true;
            }
        addConsoleToTable();
        return false;
    }
public boolean addToCart(){
    String Name=txtFldDeviceDetailsConsoleName.getText();
    String Brand= txtFldDeviceDetailsBrand.getText();
    int Quantity=Integer.parseInt(txtFldDeviceDetailsQuantity.getText());
    String releaseDate=txtFldDeviceDetailsReleaseDate.getText();
    ProjectGConsole addproduct=new ProjectGConsole(Name,Quantity,Brand,releaseDate);
    consoleList.add(addproduct);
    addConsoleToTable();
    return true;
}
 private Boolean deletedConsole(String Name) {
        for (ProjectGConsole console : consoleList) {
            if (console.getConsoleName().equals(Name)) {
                consoleList.remove(console);
                addConsoleToTable();
                return true;
            }
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        pnlLogoTitleSection = new javax.swing.JPanel();
        lblMainTitle = new javax.swing.JLabel();
        bntLogOut = new javax.swing.JButton();
        tabPnlMain = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaWelcometext = new javax.swing.JTextArea();
        pnlDevices = new javax.swing.JPanel();
        scrlPnlDeviceDetails = new javax.swing.JScrollPane();
        tblDeviceContent = new javax.swing.JTable();
        comBoxDeviceDetailsSortBy = new javax.swing.JComboBox<>();
        txtFldDeviceDetailsSearch = new javax.swing.JTextField();
        bntDeviceDetailsSearch = new javax.swing.JButton();
        txtFldDeviceDetailsConsoleName = new javax.swing.JTextField();
        txtDeviceDeatilsConsoleName = new javax.swing.JTextField();
        txtDeviceDetailsReleaseDate = new javax.swing.JTextField();
        txtFldDeviceDetailsReleaseDate = new javax.swing.JTextField();
        txtDeviceDetailsQuantity = new javax.swing.JTextField();
        txtFldDeviceDetailsQuantity = new javax.swing.JTextField();
        bntDeviceDetailsAddToCart = new javax.swing.JButton();
        txtDeviceDetailsBrand = new javax.swing.JTextField();
        txtFldDeviceDetailsBrand = new javax.swing.JTextField();
        txtDeviceDetailsSearch = new javax.swing.JTextField();
        txtDeviceDetailsSortBy = new javax.swing.JTextField();
        txtDeviceDetailsTitle = new javax.swing.JTextField();
        pnlCart = new javax.swing.JPanel();
        scrlPnlCart = new javax.swing.JScrollPane();
        tblCartDetails = new javax.swing.JTable();
        txtFldCartConsoleName = new javax.swing.JTextField();
        txtFldCartQuantity = new javax.swing.JTextField();
        txtCartBrand = new javax.swing.JTextField();
        txtFldCartBrand = new javax.swing.JTextField();
        txtCartQuantity = new javax.swing.JTextField();
        bntCartUpdate = new javax.swing.JButton();
        bntCartDelete = new javax.swing.JButton();
        txtCartConsoleName = new javax.swing.JTextField();
        bntCartOrder = new javax.swing.JButton();
        bntCartClear = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        txtFldReleaseDate = new javax.swing.JTextField();
        pnlOrderedDetail = new javax.swing.JPanel();
        lblOrderedDetailsTitle = new javax.swing.JLabel();
        scrlPnlOrderedDetails = new javax.swing.JScrollPane();
        tblDeviceContent1 = new javax.swing.JTable();
        pnlSupport = new javax.swing.JPanel();
        lblSupportTxt = new javax.swing.JLabel();
        txtFldSupportQue = new javax.swing.JTextField();
        bntSupportSubmit = new javax.swing.JButton();
        pnlSubmitDetails = new javax.swing.JPanel();
        btnEnterDetailsSubmit = new javax.swing.JButton();
        txtFldEnterDetailsName = new javax.swing.JTextField();
        txtFldEnterDetailsAddress = new javax.swing.JTextField();
        txtFldEnterDetailsNumber = new javax.swing.JTextField();
        comBoxEnterDetailsPayMeth = new javax.swing.JComboBox<>();
        txtEnterDetailsName = new javax.swing.JTextField();
        txtEnterDetailsAddress = new javax.swing.JTextField();
        txtEnterDetailsNumber = new javax.swing.JTextField();
        txtEnterDetailsPayMeth = new javax.swing.JTextField();
        txtEnterDetailsTitle = new javax.swing.JTextField();
        pnlLogInScreen = new javax.swing.JPanel();
        pnlLogInBox = new javax.swing.JPanel();
        lblLogInTitle = new javax.swing.JLabel();
        txtFldLogInUsername = new javax.swing.JTextField();
        lblLoginTxt = new javax.swing.JLabel();
        bntLogIn = new javax.swing.JButton();
        lblLogInTxt2 = new javax.swing.JLabel();
        lblLogInTxt3 = new javax.swing.JLabel();
        pwdFldLogInPassword = new javax.swing.JPasswordField();
        lblProjectGCTxt = new javax.swing.JLabel();
        lblProjectGCTxt2 = new javax.swing.JLabel();
        lblProjectGCTxt3 = new javax.swing.JLabel();
        lblProjectGCTitle = new javax.swing.JLabel();
        lblProjectGCLogo = new javax.swing.JLabel();
        lblProjectGCLogInError = new javax.swing.JLabel();

        pnlMainScreen.setBackground(new java.awt.Color(51, 102, 0));
        pnlMainScreen.setForeground(new java.awt.Color(204, 204, 204));
        pnlMainScreen.setMaximumSize(new java.awt.Dimension(860, 500));
        pnlMainScreen.setMinimumSize(new java.awt.Dimension(860, 500));
        pnlMainScreen.setPreferredSize(new java.awt.Dimension(860, 500));

        pnlLogoTitleSection.setBackground(new java.awt.Color(204, 204, 204));
        pnlLogoTitleSection.setForeground(new java.awt.Color(0, 102, 51));

        lblMainTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblMainTitle.setForeground(new java.awt.Color(51, 102, 0));
        lblMainTitle.setText("PROJECT G. CONSOLE");

        bntLogOut.setBackground(new java.awt.Color(51, 102, 0));
        bntLogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntLogOut.setForeground(new java.awt.Color(204, 204, 204));
        bntLogOut.setText("Log Out");
        bntLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLogoTitleSectionLayout = new javax.swing.GroupLayout(pnlLogoTitleSection);
        pnlLogoTitleSection.setLayout(pnlLogoTitleSectionLayout);
        pnlLogoTitleSectionLayout.setHorizontalGroup(
            pnlLogoTitleSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoTitleSectionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMainTitle)
                .addGap(129, 129, 129)
                .addComponent(bntLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlLogoTitleSectionLayout.setVerticalGroup(
            pnlLogoTitleSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoTitleSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLogoTitleSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tabPnlMain.setBackground(new java.awt.Color(51, 102, 0));
        tabPnlMain.setForeground(new java.awt.Color(204, 204, 204));

        pnlHome.setBackground(new java.awt.Color(51, 102, 0));

        txtAreaWelcometext.setBackground(new java.awt.Color(51, 102, 0));
        txtAreaWelcometext.setColumns(20);
        txtAreaWelcometext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtAreaWelcometext.setForeground(new java.awt.Color(204, 204, 204));
        txtAreaWelcometext.setRows(5);
        txtAreaWelcometext.setText("Welcome to Project G. Console !!\n\nYour ultimate destination for the lastest gaming consoles, accessories, and exclusive deals.\nWeather you're a PlayStation pr, Xbox enthusiast, or a Nintendo fanatic, we've got \neverything you need to level up your gaming experience. Explore our wide selection of top-tire \nconsoles, find accessories to enhance your setuo, and stay ahead with pre-orders for \nupcoming releases.\n\nGame on, Anytime, Anywhere !!");
        txtAreaWelcometext.setBorder(null);
        jScrollPane1.setViewportView(txtAreaWelcometext);

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        tabPnlMain.addTab("Home", pnlHome);

        pnlDevices.setBackground(new java.awt.Color(51, 102, 0));

        tblDeviceContent.setBackground(new java.awt.Color(204, 204, 204));
        tblDeviceContent.setForeground(new java.awt.Color(51, 102, 0));
        tblDeviceContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Console Name", "Brand", "Technical Features", "Additinal Feature", "Energy Efficiency", "Release Date", "Price"
            }
        ));
        tblDeviceContent.setSelectionForeground(new java.awt.Color(51, 102, 0));
        scrlPnlDeviceDetails.setViewportView(tblDeviceContent);

        comBoxDeviceDetailsSortBy.setBackground(new java.awt.Color(204, 204, 204));
        comBoxDeviceDetailsSortBy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comBoxDeviceDetailsSortBy.setForeground(new java.awt.Color(51, 102, 0));
        comBoxDeviceDetailsSortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Release Date", "Price", " " }));
        comBoxDeviceDetailsSortBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxDeviceDetailsSortByActionPerformed(evt);
            }
        });

        txtFldDeviceDetailsSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtFldDeviceDetailsSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldDeviceDetailsSearch.setForeground(new java.awt.Color(51, 102, 0));

        bntDeviceDetailsSearch.setBackground(new java.awt.Color(204, 204, 204));
        bntDeviceDetailsSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntDeviceDetailsSearch.setForeground(new java.awt.Color(51, 102, 0));
        bntDeviceDetailsSearch.setText("Search");

        txtFldDeviceDetailsConsoleName.setBackground(new java.awt.Color(204, 204, 204));
        txtFldDeviceDetailsConsoleName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldDeviceDetailsConsoleName.setForeground(new java.awt.Color(51, 102, 0));
        txtFldDeviceDetailsConsoleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldDeviceDetailsConsoleNameActionPerformed(evt);
            }
        });

        txtDeviceDeatilsConsoleName.setBackground(new java.awt.Color(51, 102, 0));
        txtDeviceDeatilsConsoleName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDeviceDeatilsConsoleName.setForeground(new java.awt.Color(204, 204, 204));
        txtDeviceDeatilsConsoleName.setText("Console Name :");
        txtDeviceDeatilsConsoleName.setBorder(null);

        txtDeviceDetailsReleaseDate.setBackground(new java.awt.Color(51, 102, 0));
        txtDeviceDetailsReleaseDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDeviceDetailsReleaseDate.setForeground(new java.awt.Color(204, 204, 204));
        txtDeviceDetailsReleaseDate.setText("Release Date :");
        txtDeviceDetailsReleaseDate.setBorder(null);
        txtDeviceDetailsReleaseDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceDetailsReleaseDateActionPerformed(evt);
            }
        });

        txtFldDeviceDetailsReleaseDate.setBackground(new java.awt.Color(204, 204, 204));
        txtFldDeviceDetailsReleaseDate.setForeground(new java.awt.Color(51, 102, 0));
        txtFldDeviceDetailsReleaseDate.setActionCommand("<Not Set>");
        txtFldDeviceDetailsReleaseDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldDeviceDetailsReleaseDateActionPerformed(evt);
            }
        });

        txtDeviceDetailsQuantity.setBackground(new java.awt.Color(51, 102, 0));
        txtDeviceDetailsQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDeviceDetailsQuantity.setForeground(new java.awt.Color(204, 204, 204));
        txtDeviceDetailsQuantity.setText("Quantity :");
        txtDeviceDetailsQuantity.setBorder(null);

        txtFldDeviceDetailsQuantity.setBackground(new java.awt.Color(204, 204, 204));
        txtFldDeviceDetailsQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldDeviceDetailsQuantity.setForeground(new java.awt.Color(51, 102, 0));

        bntDeviceDetailsAddToCart.setBackground(new java.awt.Color(204, 204, 204));
        bntDeviceDetailsAddToCart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntDeviceDetailsAddToCart.setForeground(new java.awt.Color(51, 102, 0));
        bntDeviceDetailsAddToCart.setText("Add to Cart");
        bntDeviceDetailsAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDeviceDetailsAddToCartActionPerformed(evt);
            }
        });

        txtDeviceDetailsBrand.setBackground(new java.awt.Color(51, 102, 0));
        txtDeviceDetailsBrand.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDeviceDetailsBrand.setForeground(new java.awt.Color(204, 204, 204));
        txtDeviceDetailsBrand.setText("Brand : ");
        txtDeviceDetailsBrand.setBorder(null);
        txtDeviceDetailsBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceDetailsBrandActionPerformed(evt);
            }
        });

        txtFldDeviceDetailsBrand.setBackground(new java.awt.Color(204, 204, 204));
        txtFldDeviceDetailsBrand.setForeground(new java.awt.Color(51, 102, 0));

        txtDeviceDetailsSearch.setBackground(new java.awt.Color(51, 102, 0));
        txtDeviceDetailsSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDeviceDetailsSearch.setForeground(new java.awt.Color(204, 204, 204));
        txtDeviceDetailsSearch.setText("Search :");
        txtDeviceDetailsSearch.setBorder(null);

        txtDeviceDetailsSortBy.setBackground(new java.awt.Color(51, 102, 0));
        txtDeviceDetailsSortBy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDeviceDetailsSortBy.setForeground(new java.awt.Color(204, 204, 204));
        txtDeviceDetailsSortBy.setText("Sort by :");
        txtDeviceDetailsSortBy.setBorder(null);

        txtDeviceDetailsTitle.setBackground(new java.awt.Color(51, 102, 0));
        txtDeviceDetailsTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtDeviceDetailsTitle.setForeground(new java.awt.Color(204, 204, 204));
        txtDeviceDetailsTitle.setText("Device Details:");
        txtDeviceDetailsTitle.setBorder(null);

        javax.swing.GroupLayout pnlDevicesLayout = new javax.swing.GroupLayout(pnlDevices);
        pnlDevices.setLayout(pnlDevicesLayout);
        pnlDevicesLayout.setHorizontalGroup(
            pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDevicesLayout.createSequentialGroup()
                .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDevicesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrlPnlDeviceDetails))
                    .addGroup(pnlDevicesLayout.createSequentialGroup()
                        .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDevicesLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDeviceDeatilsConsoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeviceDetailsBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldDeviceDetailsConsoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFldDeviceDetailsBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDeviceDetailsReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDeviceDetailsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldDeviceDetailsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFldDeviceDetailsReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(bntDeviceDetailsAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDevicesLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDeviceDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDevicesLayout.createSequentialGroup()
                                        .addComponent(txtDeviceDetailsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFldDeviceDetailsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bntDeviceDetailsSearch)
                                        .addGap(140, 140, 140)
                                        .addComponent(txtDeviceDetailsSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comBoxDeviceDetailsSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDevicesLayout.setVerticalGroup(
            pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDevicesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtDeviceDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDevicesLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeviceDetailsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldDeviceDetailsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntDeviceDetailsSearch)
                            .addComponent(txtDeviceDetailsSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comBoxDeviceDetailsSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrlPnlDeviceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeviceDeatilsConsoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldDeviceDetailsConsoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeviceDetailsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldDeviceDetailsQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFldDeviceDetailsBrand, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlDevicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDeviceDetailsReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFldDeviceDetailsReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtDeviceDetailsBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDevicesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntDeviceDetailsAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        tabPnlMain.addTab("Devices", pnlDevices);

        pnlCart.setBackground(new java.awt.Color(51, 102, 0));

        tblCartDetails.setBackground(new java.awt.Color(204, 204, 204));
        tblCartDetails.setForeground(new java.awt.Color(51, 102, 0));
        tblCartDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Console Name", "Brand", "Quantity", "Release Date"
            }
        ));
        scrlPnlCart.setViewportView(tblCartDetails);

        txtFldCartConsoleName.setBackground(new java.awt.Color(204, 204, 204));
        txtFldCartConsoleName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldCartConsoleName.setForeground(new java.awt.Color(51, 102, 0));

        txtFldCartQuantity.setBackground(new java.awt.Color(204, 204, 204));
        txtFldCartQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldCartQuantity.setForeground(new java.awt.Color(51, 102, 0));
        txtFldCartQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldCartQuantityActionPerformed(evt);
            }
        });

        txtCartBrand.setBackground(new java.awt.Color(51, 102, 0));
        txtCartBrand.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCartBrand.setForeground(new java.awt.Color(204, 204, 204));
        txtCartBrand.setText("Brand : ");
        txtCartBrand.setBorder(null);

        txtFldCartBrand.setBackground(new java.awt.Color(204, 204, 204));
        txtFldCartBrand.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldCartBrand.setForeground(new java.awt.Color(51, 102, 0));

        txtCartQuantity.setBackground(new java.awt.Color(51, 102, 0));
        txtCartQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCartQuantity.setForeground(new java.awt.Color(204, 204, 204));
        txtCartQuantity.setText("Quantity : ");
        txtCartQuantity.setBorder(null);

        bntCartUpdate.setBackground(new java.awt.Color(204, 204, 204));
        bntCartUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntCartUpdate.setForeground(new java.awt.Color(51, 102, 0));
        bntCartUpdate.setText("Update");
        bntCartUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCartUpdateActionPerformed(evt);
            }
        });

        bntCartDelete.setBackground(new java.awt.Color(204, 204, 204));
        bntCartDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntCartDelete.setForeground(new java.awt.Color(51, 102, 0));
        bntCartDelete.setText("Delete");
        bntCartDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCartDeleteActionPerformed(evt);
            }
        });

        txtCartConsoleName.setBackground(new java.awt.Color(51, 102, 0));
        txtCartConsoleName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCartConsoleName.setForeground(new java.awt.Color(204, 204, 204));
        txtCartConsoleName.setText("Console Name : ");
        txtCartConsoleName.setBorder(null);

        bntCartOrder.setBackground(new java.awt.Color(204, 204, 204));
        bntCartOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntCartOrder.setForeground(new java.awt.Color(51, 102, 0));
        bntCartOrder.setText("Order");

        bntCartClear.setBackground(new java.awt.Color(204, 204, 204));
        bntCartClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntCartClear.setForeground(new java.awt.Color(51, 102, 0));
        bntCartClear.setText("Clear");
        bntCartClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCartClearActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(51, 102, 0));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Release Date");
        jTextField1.setBorder(null);

        txtFldReleaseDate.setBackground(new java.awt.Color(204, 204, 204));
        txtFldReleaseDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldReleaseDate.setForeground(new java.awt.Color(51, 102, 0));

        javax.swing.GroupLayout pnlCartLayout = new javax.swing.GroupLayout(pnlCart);
        pnlCart.setLayout(pnlCartLayout);
        pnlCartLayout.setHorizontalGroup(
            pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCartLayout.createSequentialGroup()
                        .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCartBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFldCartQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldCartBrand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCartLayout.createSequentialGroup()
                        .addComponent(txtCartConsoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFldCartConsoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90)
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCartLayout.createSequentialGroup()
                        .addComponent(bntCartUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bntCartDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCartLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFldReleaseDate)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(pnlCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartLayout.createSequentialGroup()
                        .addComponent(bntCartOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntCartClear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrlPnlCart))
                .addContainerGap())
        );
        pnlCartLayout.setVerticalGroup(
            pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCartClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntCartOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrlPnlCart, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCartConsoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldCartConsoleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCartLayout.createSequentialGroup()
                        .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldCartQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCartBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldCartBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartLayout.createSequentialGroup()
                        .addGroup(pnlCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntCartUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntCartDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );

        tabPnlMain.addTab("Cart", pnlCart);

        pnlOrderedDetail.setBackground(new java.awt.Color(51, 102, 0));

        lblOrderedDetailsTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblOrderedDetailsTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblOrderedDetailsTitle.setText("Ordered Details:");

        tblDeviceContent1.setBackground(new java.awt.Color(204, 204, 204));
        tblDeviceContent1.setForeground(new java.awt.Color(51, 102, 0));
        tblDeviceContent1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Console Name", "Brand", "Quantity", "Price", "Name ", "Address", "Number"
            }
        ));
        tblDeviceContent1.setSelectionForeground(new java.awt.Color(51, 102, 0));
        scrlPnlOrderedDetails.setViewportView(tblDeviceContent1);

        javax.swing.GroupLayout pnlOrderedDetailLayout = new javax.swing.GroupLayout(pnlOrderedDetail);
        pnlOrderedDetail.setLayout(pnlOrderedDetailLayout);
        pnlOrderedDetailLayout.setHorizontalGroup(
            pnlOrderedDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderedDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderedDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlPnlOrderedDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addGroup(pnlOrderedDetailLayout.createSequentialGroup()
                        .addComponent(lblOrderedDetailsTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlOrderedDetailLayout.setVerticalGroup(
            pnlOrderedDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderedDetailLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblOrderedDetailsTitle)
                .addGap(18, 18, 18)
                .addComponent(scrlPnlOrderedDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tabPnlMain.addTab("Ordered Devices", pnlOrderedDetail);

        pnlSupport.setBackground(new java.awt.Color(51, 102, 0));

        lblSupportTxt.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblSupportTxt.setForeground(new java.awt.Color(204, 204, 204));
        lblSupportTxt.setText("How can we help?");

        txtFldSupportQue.setBackground(new java.awt.Color(204, 204, 204));
        txtFldSupportQue.setForeground(new java.awt.Color(51, 102, 0));
        txtFldSupportQue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldSupportQueActionPerformed(evt);
            }
        });

        bntSupportSubmit.setBackground(new java.awt.Color(204, 204, 204));
        bntSupportSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntSupportSubmit.setForeground(new java.awt.Color(51, 102, 0));
        bntSupportSubmit.setText("Submit");

        javax.swing.GroupLayout pnlSupportLayout = new javax.swing.GroupLayout(pnlSupport);
        pnlSupport.setLayout(pnlSupportLayout);
        pnlSupportLayout.setHorizontalGroup(
            pnlSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSupportLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(pnlSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntSupportSubmit)
                    .addComponent(lblSupportTxt)
                    .addComponent(txtFldSupportQue, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        pnlSupportLayout.setVerticalGroup(
            pnlSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSupportLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblSupportTxt)
                .addGap(18, 18, 18)
                .addComponent(txtFldSupportQue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntSupportSubmit)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        tabPnlMain.addTab("Support", pnlSupport);

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogoTitleSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPnlMain)
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addComponent(pnlLogoTitleSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPnlMain))
        );

        pnlSubmitDetails.setBackground(new java.awt.Color(51, 102, 0));
        pnlSubmitDetails.setForeground(new java.awt.Color(204, 204, 204));
        pnlSubmitDetails.setMaximumSize(new java.awt.Dimension(860, 500));
        pnlSubmitDetails.setMinimumSize(new java.awt.Dimension(860, 500));
        pnlSubmitDetails.setPreferredSize(new java.awt.Dimension(860, 500));

        btnEnterDetailsSubmit.setBackground(new java.awt.Color(204, 204, 204));
        btnEnterDetailsSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEnterDetailsSubmit.setForeground(new java.awt.Color(51, 102, 0));
        btnEnterDetailsSubmit.setText("Submit");

        txtFldEnterDetailsName.setBackground(new java.awt.Color(204, 204, 204));
        txtFldEnterDetailsName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldEnterDetailsName.setForeground(new java.awt.Color(51, 102, 0));

        txtFldEnterDetailsAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtFldEnterDetailsAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldEnterDetailsAddress.setForeground(new java.awt.Color(51, 102, 0));

        txtFldEnterDetailsNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtFldEnterDetailsNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFldEnterDetailsNumber.setForeground(new java.awt.Color(51, 102, 0));
        txtFldEnterDetailsNumber.setToolTipText("");

        comBoxEnterDetailsPayMeth.setBackground(new java.awt.Color(204, 204, 204));
        comBoxEnterDetailsPayMeth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comBoxEnterDetailsPayMeth.setForeground(new java.awt.Color(51, 102, 0));
        comBoxEnterDetailsPayMeth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Online ", "Cash" }));

        txtEnterDetailsName.setBackground(new java.awt.Color(51, 102, 0));
        txtEnterDetailsName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEnterDetailsName.setForeground(new java.awt.Color(204, 204, 204));
        txtEnterDetailsName.setText("Name:");
        txtEnterDetailsName.setBorder(null);

        txtEnterDetailsAddress.setBackground(new java.awt.Color(51, 102, 0));
        txtEnterDetailsAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEnterDetailsAddress.setForeground(new java.awt.Color(204, 204, 204));
        txtEnterDetailsAddress.setText("Address :");
        txtEnterDetailsAddress.setBorder(null);

        txtEnterDetailsNumber.setBackground(new java.awt.Color(51, 102, 0));
        txtEnterDetailsNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEnterDetailsNumber.setForeground(new java.awt.Color(204, 204, 204));
        txtEnterDetailsNumber.setText("Number :");
        txtEnterDetailsNumber.setBorder(null);

        txtEnterDetailsPayMeth.setBackground(new java.awt.Color(51, 102, 0));
        txtEnterDetailsPayMeth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEnterDetailsPayMeth.setForeground(new java.awt.Color(204, 204, 204));
        txtEnterDetailsPayMeth.setText("Payment Method :");
        txtEnterDetailsPayMeth.setBorder(null);
        txtEnterDetailsPayMeth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterDetailsPayMethActionPerformed(evt);
            }
        });

        txtEnterDetailsTitle.setBackground(new java.awt.Color(51, 102, 0));
        txtEnterDetailsTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtEnterDetailsTitle.setForeground(new java.awt.Color(204, 204, 204));
        txtEnterDetailsTitle.setText("Enter Details:");
        txtEnterDetailsTitle.setBorder(null);
        txtEnterDetailsTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterDetailsTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSubmitDetailsLayout = new javax.swing.GroupLayout(pnlSubmitDetails);
        pnlSubmitDetails.setLayout(pnlSubmitDetailsLayout);
        pnlSubmitDetailsLayout.setHorizontalGroup(
            pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubmitDetailsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSubmitDetailsLayout.createSequentialGroup()
                        .addGroup(pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEnterDetailsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnterDetailsAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnterDetailsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSubmitDetailsLayout.createSequentialGroup()
                                .addComponent(txtFldEnterDetailsName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEnterDetailsSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSubmitDetailsLayout.createSequentialGroup()
                                .addGroup(pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldEnterDetailsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFldEnterDetailsAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlSubmitDetailsLayout.createSequentialGroup()
                                        .addGap(230, 230, 230)
                                        .addComponent(txtEnterDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 180, Short.MAX_VALUE))))
                    .addGroup(pnlSubmitDetailsLayout.createSequentialGroup()
                        .addComponent(txtEnterDetailsPayMeth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comBoxEnterDetailsPayMeth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(196, 196, 196))
        );
        pnlSubmitDetailsLayout.setVerticalGroup(
            pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSubmitDetailsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtEnterDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterDetailsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldEnterDetailsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnterDetailsSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterDetailsAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldEnterDetailsAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterDetailsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldEnterDetailsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlSubmitDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnterDetailsPayMeth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBoxEnterDetailsPayMeth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(860, 500, 500, 500));
        setMaximumSize(new java.awt.Dimension(860, 500));
        setMinimumSize(new java.awt.Dimension(860, 500));

        pnlLogInScreen.setBackground(new java.awt.Color(51, 102, 0));
        pnlLogInScreen.setMaximumSize(new java.awt.Dimension(860, 500));
        pnlLogInScreen.setMinimumSize(new java.awt.Dimension(860, 500));
        pnlLogInScreen.setPreferredSize(new java.awt.Dimension(860, 500));

        pnlLogInBox.setBackground(new java.awt.Color(204, 204, 204));

        lblLogInTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblLogInTitle.setForeground(new java.awt.Color(51, 102, 0));
        lblLogInTitle.setText("Log In");

        txtFldLogInUsername.setBackground(new java.awt.Color(153, 153, 153));
        txtFldLogInUsername.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtFldLogInUsername.setForeground(new java.awt.Color(0, 102, 0));
        txtFldLogInUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(51, 102, 0))); // NOI18N
        txtFldLogInUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldLogInUsernameActionPerformed(evt);
            }
        });

        lblLoginTxt.setBackground(new java.awt.Color(204, 204, 204));
        lblLoginTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLoginTxt.setForeground(new java.awt.Color(51, 102, 0));
        lblLoginTxt.setText("Don't have an account? Sign up");

        bntLogIn.setBackground(new java.awt.Color(51, 102, 0));
        bntLogIn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bntLogIn.setForeground(new java.awt.Color(204, 204, 204));
        bntLogIn.setText("Log In");
        bntLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLogInActionPerformed(evt);
            }
        });

        lblLogInTxt2.setBackground(new java.awt.Color(204, 204, 204));
        lblLogInTxt2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLogInTxt2.setForeground(new java.awt.Color(51, 102, 0));
        lblLogInTxt2.setText("Forgot Password");

        lblLogInTxt3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLogInTxt3.setForeground(new java.awt.Color(51, 102, 0));
        lblLogInTxt3.setText("Enter the details below");

        pwdFldLogInPassword.setBackground(new java.awt.Color(153, 153, 153));
        pwdFldLogInPassword.setForeground(new java.awt.Color(51, 102, 0));
        pwdFldLogInPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 102, 0))); // NOI18N
        pwdFldLogInPassword.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout pnlLogInBoxLayout = new javax.swing.GroupLayout(pnlLogInBox);
        pnlLogInBox.setLayout(pnlLogInBoxLayout);
        pnlLogInBoxLayout.setHorizontalGroup(
            pnlLogInBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInBoxLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlLogInBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogInTxt3)
                    .addGroup(pnlLogInBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblLogInTxt2)
                        .addGroup(pnlLogInBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFldLogInUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(lblLogInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdFldLogInPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInBoxLayout.createSequentialGroup()
                .addGap(0, 52, Short.MAX_VALUE)
                .addComponent(lblLoginTxt)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogInBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        pnlLogInBoxLayout.setVerticalGroup(
            pnlLogInBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInBoxLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblLogInTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogInTxt3)
                .addGap(18, 18, 18)
                .addComponent(txtFldLogInUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdFldLogInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogInTxt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoginTxt)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        lblProjectGCTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProjectGCTxt.setForeground(new java.awt.Color(204, 204, 204));
        lblProjectGCTxt.setText("Bring your desired gaming console home");

        lblProjectGCTxt2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblProjectGCTxt2.setForeground(new java.awt.Color(204, 204, 204));
        lblProjectGCTxt2.setText("and dive into the world of gaming!");

        lblProjectGCTxt3.setForeground(new java.awt.Color(204, 204, 204));
        lblProjectGCTxt3.setText("Playstation, Xbox, nindendo and many more...");

        lblProjectGCTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblProjectGCTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblProjectGCTitle.setText("PROJECT G. CONSOLE");

        lblProjectGCLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/projectGC/resources/PROJECT G. CONSOLE_1.png"))); // NOI18N

        lblProjectGCLogInError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProjectGCLogInError.setForeground(new java.awt.Color(255, 0, 0));
        lblProjectGCLogInError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlLogInScreenLayout = new javax.swing.GroupLayout(pnlLogInScreen);
        pnlLogInScreen.setLayout(pnlLogInScreenLayout);
        pnlLogInScreenLayout.setHorizontalGroup(
            pnlLogInScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInScreenLayout.createSequentialGroup()
                .addGroup(pnlLogInScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogInScreenLayout.createSequentialGroup()
                        .addComponent(lblProjectGCLogo)
                        .addGap(0, 407, Short.MAX_VALUE))
                    .addGroup(pnlLogInScreenLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(pnlLogInScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProjectGCTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                            .addGroup(pnlLogInScreenLayout.createSequentialGroup()
                                .addGroup(pnlLogInScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProjectGCTxt2)
                                    .addComponent(lblProjectGCTxt3)
                                    .addComponent(lblProjectGCTitle))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(pnlLogInScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlLogInBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProjectGCLogInError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71))
        );
        pnlLogInScreenLayout.setVerticalGroup(
            pnlLogInScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogInScreenLayout.createSequentialGroup()
                .addGroup(pnlLogInScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogInScreenLayout.createSequentialGroup()
                        .addComponent(lblProjectGCLogo)
                        .addGap(21, 21, 21)
                        .addComponent(lblProjectGCTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProjectGCTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProjectGCTxt2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProjectGCTxt3))
                    .addGroup(pnlLogInScreenLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblProjectGCLogInError, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlLogInBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlLogInScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlLogInScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFldLogInUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldLogInUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldLogInUsernameActionPerformed

    private void bntLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLogInActionPerformed
        // TODO add your handling code here:
        // Get the username and password input
        String username = txtFldLogInUsername.getText();
        String password = new String(pwdFldLogInPassword.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblProjectGCLogInError.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("supra") || !password.equals("supra")) {
            lblProjectGCLogInError.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblProjectGCLogInError.setText(""); // Clear any previous error messages
            loadScreen("MainScreen"); // Load the main screen
        }
    }//GEN-LAST:event_bntLogInActionPerformed

    private void txtFldSupportQueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldSupportQueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldSupportQueActionPerformed

    private void txtFldDeviceDetailsConsoleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldDeviceDetailsConsoleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldDeviceDetailsConsoleNameActionPerformed

    private void txtDeviceDetailsReleaseDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceDetailsReleaseDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceDetailsReleaseDateActionPerformed

    private void bntDeviceDetailsAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDeviceDetailsAddToCartActionPerformed

    addToCart();        // TODO add your handling code here:
    }//GEN-LAST:event_bntDeviceDetailsAddToCartActionPerformed

    private void txtDeviceDetailsBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceDetailsBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceDetailsBrandActionPerformed

    private void txtFldCartQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldCartQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldCartQuantityActionPerformed

    private void txtEnterDetailsPayMethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterDetailsPayMethActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterDetailsPayMethActionPerformed

    private void txtEnterDetailsTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterDetailsTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterDetailsTitleActionPerformed

    private void comBoxDeviceDetailsSortByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxDeviceDetailsSortByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comBoxDeviceDetailsSortByActionPerformed

    private void bntLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLogOutActionPerformed
        // TODO add your handling code here:
        pwdFldLogInPassword.setText("");
        txtFldLogInUsername.setText("");
        loadScreen("LogInScreen"); // Load the main screen
    }//GEN-LAST:event_bntLogOutActionPerformed

    private void txtFldDeviceDetailsReleaseDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldDeviceDetailsReleaseDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldDeviceDetailsReleaseDateActionPerformed

    private void bntCartClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCartClearActionPerformed
        // TODO add your handling code here:
        clearTxtField();
    }//GEN-LAST:event_bntCartClearActionPerformed

    private void bntCartUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCartUpdateActionPerformed
String Name=txtFldDeviceDetailsConsoleName.getText();
 String Brand= txtFldDeviceDetailsBrand.getText();
 int Quantity=Integer.parseInt(txtFldDeviceDetailsQuantity.getText());
 String ReleaseDate=txtFldReleaseDate.getText();
    ProjectGConsole Console=new ProjectGConsole(Name,Quantity,Brand,ReleaseDate);
    UpdateCart(Console);        // TODO add your handling code here:
    }//GEN-LAST:event_bntCartUpdateActionPerformed

    private void bntCartDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCartDeleteActionPerformed
String name=txtFldCartConsoleName.getText();
        deletedConsole(name);        // TODO add your handling code here:
    }//GEN-LAST:event_bntCartDeleteActionPerformed
    // Method to set up the CardLayout and add panels
       private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
         getContentPane().add(pnlLogInScreen, "LogInScreen");
         getContentPane().add(pnlMainScreen, "MainScreen");
         getContentPane().add(pnlSubmitDetails,"SubmitDetails");

        // Start with the login screen
        cardLayout.show(getContentPane(), "LogInScreen");
   } 
       // Method to initialize data, including student list and table
    private void initializeData() {
   
        
        
    }

    private void clearTxtField(){
        txtFldCartConsoleName.setText("");
        txtFldCartBrand.setText("");
        txtFldCartQuantity.setText("");
    }
        
       // Method to switch screens
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
                                        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projectGC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projectGC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projectGC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projectGC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new projectGC().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCartClear;
    private javax.swing.JButton bntCartDelete;
    private javax.swing.JButton bntCartOrder;
    private javax.swing.JButton bntCartUpdate;
    private javax.swing.JButton bntDeviceDetailsAddToCart;
    private javax.swing.JButton bntDeviceDetailsSearch;
    private javax.swing.JButton bntLogIn;
    private javax.swing.JButton bntLogOut;
    private javax.swing.JButton bntSupportSubmit;
    private javax.swing.JButton btnEnterDetailsSubmit;
    private javax.swing.JComboBox<String> comBoxDeviceDetailsSortBy;
    private javax.swing.JComboBox<String> comBoxEnterDetailsPayMeth;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblLogInTitle;
    private javax.swing.JLabel lblLogInTxt2;
    private javax.swing.JLabel lblLogInTxt3;
    private javax.swing.JLabel lblLoginTxt;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblOrderedDetailsTitle;
    private javax.swing.JLabel lblProjectGCLogInError;
    private javax.swing.JLabel lblProjectGCLogo;
    private javax.swing.JLabel lblProjectGCTitle;
    private javax.swing.JLabel lblProjectGCTxt;
    private javax.swing.JLabel lblProjectGCTxt2;
    private javax.swing.JLabel lblProjectGCTxt3;
    private javax.swing.JLabel lblSupportTxt;
    private javax.swing.JPanel pnlCart;
    private javax.swing.JPanel pnlDevices;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLogInBox;
    private javax.swing.JPanel pnlLogInScreen;
    private javax.swing.JPanel pnlLogoTitleSection;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JPanel pnlOrderedDetail;
    private javax.swing.JPanel pnlSubmitDetails;
    private javax.swing.JPanel pnlSupport;
    private javax.swing.JPasswordField pwdFldLogInPassword;
    private javax.swing.JScrollPane scrlPnlCart;
    private javax.swing.JScrollPane scrlPnlDeviceDetails;
    private javax.swing.JScrollPane scrlPnlOrderedDetails;
    private javax.swing.JTabbedPane tabPnlMain;
    private javax.swing.JTable tblCartDetails;
    private javax.swing.JTable tblDeviceContent;
    private javax.swing.JTable tblDeviceContent1;
    private javax.swing.JTextArea txtAreaWelcometext;
    private javax.swing.JTextField txtCartBrand;
    private javax.swing.JTextField txtCartConsoleName;
    private javax.swing.JTextField txtCartQuantity;
    private javax.swing.JTextField txtDeviceDeatilsConsoleName;
    private javax.swing.JTextField txtDeviceDetailsBrand;
    private javax.swing.JTextField txtDeviceDetailsQuantity;
    private javax.swing.JTextField txtDeviceDetailsReleaseDate;
    private javax.swing.JTextField txtDeviceDetailsSearch;
    private javax.swing.JTextField txtDeviceDetailsSortBy;
    private javax.swing.JTextField txtDeviceDetailsTitle;
    private javax.swing.JTextField txtEnterDetailsAddress;
    private javax.swing.JTextField txtEnterDetailsName;
    private javax.swing.JTextField txtEnterDetailsNumber;
    private javax.swing.JTextField txtEnterDetailsPayMeth;
    private javax.swing.JTextField txtEnterDetailsTitle;
    private javax.swing.JTextField txtFldCartBrand;
    private javax.swing.JTextField txtFldCartConsoleName;
    private javax.swing.JTextField txtFldCartQuantity;
    private javax.swing.JTextField txtFldDeviceDetailsBrand;
    private javax.swing.JTextField txtFldDeviceDetailsConsoleName;
    private javax.swing.JTextField txtFldDeviceDetailsQuantity;
    private javax.swing.JTextField txtFldDeviceDetailsReleaseDate;
    private javax.swing.JTextField txtFldDeviceDetailsSearch;
    private javax.swing.JTextField txtFldEnterDetailsAddress;
    private javax.swing.JTextField txtFldEnterDetailsName;
    private javax.swing.JTextField txtFldEnterDetailsNumber;
    private javax.swing.JTextField txtFldLogInUsername;
    private javax.swing.JTextField txtFldReleaseDate;
    private javax.swing.JTextField txtFldSupportQue;
    // End of variables declaration//GEN-END:variables

}
